<?php

declare(strict_types=1);

/*
 * ApimaticCalcuLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticCalcuLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const CALCULATOR = 'Calculator';
}
